version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.togglz:togglz-console
    versions:
    - 2.9.4
    - 2.9.5
    - 2.9.6
  - dependency-name: org.togglz:togglz-spring-boot-starter
    versions:
    - 2.9.4
    - 2.9.5
    - 2.9.6
