version: "3.8"
services:
  api:
    build: .
    container_name: api
    ports:
      - 8080:8080
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: mysql
    ports:
      - 3306:3306
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10