server:
  port: 8080

spring:
  application:
    name: finances-api

  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/finances_db}?createDatabaseIfNotExist=true
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        format_sql: true
