CREATE TABLE BILL
(
    BILL_ID          BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DESCRIPTION      VARCHAR(50)        NOT NULL,
    ORIGINAL_AMOUNT  DECIMAL(10, 2)     NOT NULL,
    CORRECTED_AMOUNT DECIMAL(10, 2)     NULL,
    DUE_DATE         DATE               NOT NULL,
    PAYMENT_DATE     DATE               NOT NULL
);