CREATE TABLE INTEREST_CONFIGURATION
(
    INTEREST_ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    START_RANGE INT                NOT NULL,
    END_RANGE   INT                NOT NULL,
    FINE        DECIMAL(10, 4)     NOT NULL,
    INTEREST    DECIMAL(10, 4)     NOT NULL
);
