INSERT INTO INTEREST_CONFIGURATION (INTEREST_ID, START_RANGE, END_RANGE, FINE, INTEREST)
VALUES (null, 1, 3, 0.02, 0.001);

INSERT INTO INTEREST_CONFIGURATION (INTEREST_ID, START_RANGE, END_RANGE, FINE, INTEREST)
VALUES (null, 4, 5, 0.03, 0.002);

INSERT INTO INTEREST_CONFIGURATION(INTEREST_ID, START_RANGE, END_RANGE, FINE, INTEREST)
VALUES (null, 6, 999999, 0.05, 0.003);